import { NextRequest, NextResponse } from 'next/server'
import { verifyAdminToken } from '@/lib/auth/middleware'
import { getAllAdmissions, getAdmissionsByStatus, createAdmission } from '@/lib/firestore/admissions'

export async function GET(request: NextRequest) {
  try {
    // Verify admin token - admissions data is sensitive
    const decodedToken = await verifyAdminToken(request)
    if (!decodedToken) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')

    let admissions
    if (status) {
      admissions = await getAdmissionsByStatus(status)
    } else {
      admissions = await getAllAdmissions()
    }

    return NextResponse.json({ admissions })
  } catch (error: any) {
    console.error('Error fetching admissions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch admissions' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    // Note: This endpoint is intentionally public for application submissions
    // Input validation is handled below to prevent abuse
    const body = await request.json()
    
    // Validate required fields
    if (!body.name || !body.email || !body.phone) {
      return NextResponse.json(
        { error: 'Missing required fields: name, email, phone' },
        { status: 400 }
      )
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(body.email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      )
    }

    // Sanitize and validate input lengths
    // Remove id if present (it will be generated by Firestore)
    const { id, ...bodyWithoutId } = body
    
    const sanitizedData = {
      name: String(bodyWithoutId.name).trim().substring(0, 200),
      email: String(bodyWithoutId.email).trim().substring(0, 200),
      phone: String(bodyWithoutId.phone).trim().substring(0, 50),
      grade: bodyWithoutId.grade ? String(bodyWithoutId.grade).trim().substring(0, 50) : undefined,
      message: bodyWithoutId.message ? String(bodyWithoutId.message).trim().substring(0, 2000) : undefined,
      status: 'pending' as const
      // Note: createdAt is added automatically by createAdmission function
    }
    
    // Type assertion needed because createAdmission expects full AdmissionDocument
    // but this endpoint accepts simplified form data
    const admissionId = await createAdmission(sanitizedData as any)
    return NextResponse.json({ id: admissionId, ...sanitizedData })
  } catch (error: any) {
    console.error('Error creating admission:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to create admission' },
      { status: 500 }
    )
  }
}
