import { NextRequest, NextResponse } from 'next/server'
import { verifyAdminToken } from '@/lib/auth/middleware'
import { getAllAdmissions, getAdmissionsByStatus, createAdmission } from '@/lib/firestore/admissions'

export async function GET(request: NextRequest) {
  try {
    // Verify admin token - admissions data is sensitive
    const decodedToken = await verifyAdminToken(request)
    if (!decodedToken) {
      return NextResponse.json(
        { error: 'Unauthorized' },
        { status: 401 }
      )
    }

    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')

    let admissions
    if (status) {
      admissions = await getAdmissionsByStatus(status)
    } else {
      admissions = await getAllAdmissions()
    }

    return NextResponse.json({ admissions })
  } catch (error: any) {
    console.error('Error fetching admissions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch admissions' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    // Note: This endpoint is intentionally public for application submissions
    // Input validation is handled below to prevent abuse
    const body = await request.json()
    
    // Validate required fields
    if (!body.name || !body.email || !body.phone) {
      return NextResponse.json(
        { error: 'Missing required fields: name, email, phone' },
        { status: 400 }
      )
    }

    // Validate email format
    const emailRegex = /^[^\s@]+@[^\s@]+\.[^\s@]+$/
    if (!emailRegex.test(body.email)) {
      return NextResponse.json(
        { error: 'Invalid email format' },
        { status: 400 }
      )
    }

    // Sanitize and validate input lengths
    const sanitizedData = {
      name: String(body.name).trim().substring(0, 200),
      email: String(body.email).trim().substring(0, 200),
      phone: String(body.phone).trim().substring(0, 50),
      grade: body.grade ? String(body.grade).trim().substring(0, 50) : undefined,
      message: body.message ? String(body.message).trim().substring(0, 2000) : undefined,
      status: 'pending', // Set default status
      createdAt: new Date().toISOString()
    }
    
    // Remove id if present (it will be generated by Firestore)
    const { id, ...admissionData } = sanitizedData
    
    const admissionId = await createAdmission(admissionData)
    return NextResponse.json({ id: admissionId, ...admissionData })
  } catch (error: any) {
    console.error('Error creating admission:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to create admission' },
      { status: 500 }
    )
  }
}
