import { NextRequest, NextResponse } from 'next/server'
import { verifyAdminToken } from '@/lib/auth/middleware'
import { getAllAdmissions, getAdmissionsByStatus, createAdmission } from '@/lib/firestore/admissions'

export async function GET(request: NextRequest) {
  try {
    const { searchParams } = new URL(request.url)
    const status = searchParams.get('status')

    let admissions
    if (status) {
      admissions = await getAdmissionsByStatus(status)
    } else {
      admissions = await getAllAdmissions()
    }

    return NextResponse.json({ admissions })
  } catch (error: any) {
    console.error('Error fetching admissions:', error)
    return NextResponse.json(
      { error: 'Failed to fetch admissions' },
      { status: 500 }
    )
  }
}

export async function POST(request: NextRequest) {
  try {
    const body = await request.json()
    
    // Remove id if present (it will be generated by Firestore)
    const { id, ...admissionData } = body
    
    const admissionId = await createAdmission(admissionData)
    return NextResponse.json({ id: admissionId, ...admissionData })
  } catch (error: any) {
    console.error('Error creating admission:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to create admission' },
      { status: 500 }
    )
  }
}
